-- Schema Dump
-- Generated: 2026-01-27T08:02:58.501Z
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `Users`;
DROP TABLE IF EXISTS `Groups`;
DROP TABLE IF EXISTS `Loans`;
DROP TABLE IF EXISTS `Contributions`;
DROP TABLE IF EXISTS `Transactions`;
DROP TABLE IF EXISTS `Fines`;
DROP TABLE IF EXISTS `Announcements`;
DROP TABLE IF EXISTS `Meetings`;
DROP TABLE IF EXISTS `Votes`;
DROP TABLE IF EXISTS `VoteOptions`;
DROP TABLE IF EXISTS `VoteResponses`;
DROP TABLE IF EXISTS `LearnGrowContents`;
DROP TABLE IF EXISTS `ChatMessages`;
DROP TABLE IF EXISTS `Notifications`;
DROP TABLE IF EXISTS `Branches`;
DROP TABLE IF EXISTS `MemberApplications`;
DROP TABLE IF EXISTS `AuditLogs`;
DROP TABLE IF EXISTS `SupportTickets`;
DROP TABLE IF EXISTS `Settings`;
DROP TABLE IF EXISTS `LoanProducts`;
DROP TABLE IF EXISTS `MessageTemplates`;
DROP TABLE IF EXISTS `ComplianceRules`;
DROP TABLE IF EXISTS `ComplianceViolations`;
DROP TABLE IF EXISTS `Documents`;
DROP TABLE IF EXISTS `TrainingProgress`;
DROP TABLE IF EXISTS `ScheduledAudits`;

CREATE TABLE IF NOT EXISTS `Users` (`id` INTEGER auto_increment , `email` VARCHAR(255), `phone` VARCHAR(20) NOT NULL, `name` VARCHAR(100) NOT NULL, `password` VARCHAR(255), `role` ENUM('Member', 'Group Admin', 'Cashier', 'Secretary', 'Agent', 'System Admin') NOT NULL DEFAULT 'Member', `groupId` INTEGER, `branchId` INTEGER, `status` ENUM('active', 'inactive', 'suspended', 'pending', 'burned') DEFAULT 'active', `totalSavings` DECIMAL(15,2) DEFAULT 0, `creditScore` INTEGER DEFAULT 0, `otp` VARCHAR(6), `otpExpiry` DATETIME, `language` VARCHAR(10) DEFAULT 'en', `profileImage` VARCHAR(255), `occupation` VARCHAR(100), `address` TEXT, `dateOfBirth` DATETIME, `nationalId` VARCHAR(50), `lastLogin` DATETIME, `resetToken` VARCHAR(255), `resetTokenExpiry` DATETIME, `permissions` JSON, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`groupId`) REFERENCES `Groups` (`id`) ON DELETE SET NULL ON UPDATE CASCADE, FOREIGN KEY (`branchId`) REFERENCES `Branches` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Groups` (`id` INTEGER auto_increment , `name` VARCHAR(100) NOT NULL UNIQUE, `code` VARCHAR(20) NOT NULL UNIQUE, `description` TEXT, `branchId` INTEGER, `agentId` INTEGER, `totalSavings` DECIMAL(15,2) DEFAULT 0, `totalMembers` INTEGER DEFAULT 0, `contributionAmount` DECIMAL(15,2), `contributionFrequency` ENUM('daily', 'weekly', 'monthly') DEFAULT 'monthly', `status` ENUM('active', 'inactive', 'suspended') DEFAULT 'active', `registrationDate` DATETIME, `district` VARCHAR(100), `sector` VARCHAR(100), `cell` VARCHAR(100), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`branchId`) REFERENCES `Branches` (`id`) ON DELETE SET NULL ON UPDATE CASCADE, FOREIGN KEY (`agentId`) REFERENCES `Users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Loans` (`id` INTEGER auto_increment , `memberId` INTEGER NOT NULL, `groupId` INTEGER NOT NULL, `amount` DECIMAL(15,2) NOT NULL, `purpose` VARCHAR(255) NOT NULL, `interestRate` DECIMAL(5,2) DEFAULT 5, `duration` INTEGER NOT NULL COMMENT 'Duration in months', `monthlyPayment` DECIMAL(15,2) NOT NULL, `totalAmount` DECIMAL(15,2) NOT NULL COMMENT 'Principal + Interest', `status` ENUM('pending', 'approved', 'rejected', 'disbursed', 'active', 'completed', 'defaulted') DEFAULT 'pending', `requestDate` DATETIME, `approvalDate` DATETIME, `approvedBy` INTEGER, `disbursementDate` DATETIME, `paidAmount` DECIMAL(15,2) DEFAULT 0, `remainingAmount` DECIMAL(15,2) NOT NULL, `nextPaymentDate` DATETIME, `aiRecommendation` ENUM('approve', 'reject', 'review'), `rejectionReason` TEXT, `documents` JSON COMMENT 'Array of document URLs', `guarantorId` INTEGER COMMENT 'Reference to the guarantor user (must be a member of the same group)', `guarantorName` VARCHAR(100) COMMENT 'Guarantor full name', `guarantorPhone` VARCHAR(20) COMMENT 'Guarantor phone number', `guarantorNationalId` VARCHAR(50) COMMENT 'Guarantor national ID', `guarantorRelationship` VARCHAR(100) COMMENT 'Relationship to borrower (e.g., family member, friend, colleague)', `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`memberId`) REFERENCES `Users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`groupId`) REFERENCES `Groups` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`approvedBy`) REFERENCES `Users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE, FOREIGN KEY (`guarantorId`) REFERENCES `Users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Contributions` (`id` INTEGER auto_increment , `memberId` INTEGER NOT NULL, `groupId` INTEGER NOT NULL, `amount` DECIMAL(15,2) NOT NULL, `paymentMethod` ENUM('cash', 'mtn_mobile_money', 'airtel_money', 'bank_transfer') NOT NULL, `transactionId` VARCHAR(100) COMMENT 'MTN/Airtel transaction ID or bank reference', `status` ENUM('pending', 'approved', 'rejected') DEFAULT 'pending', `approvedBy` INTEGER, `approvalDate` DATETIME, `rejectionReason` TEXT, `receiptNumber` VARCHAR(50) UNIQUE, `notes` TEXT, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`memberId`) REFERENCES `Users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`groupId`) REFERENCES `Groups` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`approvedBy`) REFERENCES `Users` (`id`)) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Transactions` (`id` INTEGER auto_increment , `userId` INTEGER NOT NULL, `type` ENUM('contribution', 'loan_payment', 'loan_disbursement', 'fine_payment', 'interest', 'refund', 'fee') NOT NULL, `amount` DECIMAL(15,2) NOT NULL, `balance` DECIMAL(15,2) NOT NULL COMMENT 'Balance after transaction', `status` ENUM('pending', 'completed', 'failed', 'cancelled') DEFAULT 'pending', `referenceId` VARCHAR(100) COMMENT 'Reference to related entity (loanId, contributionId, etc.)', `referenceType` VARCHAR(50) COMMENT 'Type of reference (Loan, Contribution, Fine, etc.)', `description` TEXT, `paymentMethod` ENUM('cash', 'mtn_mobile_money', 'airtel_money', 'bank_transfer'), `transactionDate` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `Users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Fines` (`id` INTEGER auto_increment , `memberId` INTEGER NOT NULL, `groupId` INTEGER NOT NULL, `amount` DECIMAL(15,2) NOT NULL, `reason` TEXT NOT NULL, `status` ENUM('pending', 'approved', 'paid', 'waived', 'rejected') DEFAULT 'pending', `issuedBy` INTEGER NOT NULL, `approvedBy` INTEGER, `issuedDate` DATETIME, `dueDate` DATETIME, `paidDate` DATETIME, `waiverReason` TEXT, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`memberId`) REFERENCES `Users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`groupId`) REFERENCES `Groups` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`issuedBy`) REFERENCES `Users` (`id`), FOREIGN KEY (`approvedBy`) REFERENCES `Users` (`id`)) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Announcements` (`id` INTEGER auto_increment , `groupId` INTEGER, `title` VARCHAR(255) NOT NULL, `content` TEXT NOT NULL, `priority` ENUM('low', 'medium', 'high') DEFAULT 'medium', `status` ENUM('draft', 'sent') DEFAULT 'draft', `createdBy` INTEGER NOT NULL, `sentAt` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`groupId`) REFERENCES `Groups` (`id`) ON DELETE SET NULL ON UPDATE CASCADE, FOREIGN KEY (`createdBy`) REFERENCES `Users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Meetings` (`id` INTEGER auto_increment , `groupId` INTEGER NOT NULL, `title` VARCHAR(255) NOT NULL, `agenda` TEXT, `scheduledDate` DATETIME NOT NULL, `scheduledTime` TIME NOT NULL, `location` VARCHAR(255), `status` ENUM('scheduled', 'ongoing', 'completed', 'cancelled') DEFAULT 'scheduled', `minutes` TEXT, `attendance` JSON COMMENT 'Array of member IDs who attended', `attendanceTakenBy` INTEGER COMMENT 'User ID who took the attendance', `attendanceTakenAt` DATETIME COMMENT 'Date and time when attendance was taken', `createdBy` INTEGER NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`groupId`) REFERENCES `Groups` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`attendanceTakenBy`) REFERENCES `Users` (`id`), FOREIGN KEY (`createdBy`) REFERENCES `Users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Votes` (`id` INTEGER auto_increment , `groupId` INTEGER NOT NULL, `title` VARCHAR(255) NOT NULL, `description` TEXT, `type` ENUM('loan_approval', 'loan_approval_override', 'member_admission', 'fine_waiver', 'policy_change', 'withdrawal_approval', 'contribution_change', 'saving_amount_change', 'fine_change', 'fine_amount_change', 'interest_rate_change', 'other') NOT NULL, `status` ENUM('open', 'closed', 'cancelled') DEFAULT 'open', `startDate` DATETIME, `endDate` DATETIME NOT NULL, `createdBy` INTEGER NOT NULL, `totalVotes` INTEGER DEFAULT 0, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`groupId`) REFERENCES `Groups` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`createdBy`) REFERENCES `Users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `VoteOptions` (`id` INTEGER auto_increment , `voteId` INTEGER NOT NULL, `option` VARCHAR(255) NOT NULL, `voteCount` INTEGER DEFAULT 0, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`voteId`) REFERENCES `Votes` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `VoteResponses` (`id` INTEGER auto_increment , `voteId` INTEGER NOT NULL, `optionId` INTEGER NOT NULL, `memberId` INTEGER NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`voteId`) REFERENCES `Votes` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`optionId`) REFERENCES `VoteOptions` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`memberId`) REFERENCES `Users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `LearnGrowContents` (`id` INTEGER auto_increment , `title` VARCHAR(255) NOT NULL, `description` TEXT, `content` TEXT, `type` ENUM('article', 'video', 'pdf', 'quiz', 'infographic') NOT NULL, `category` VARCHAR(100) COMMENT 'e.g., Saving, Budgeting, Loans, Investment', `fileUrl` VARCHAR(500), `thumbnailUrl` VARCHAR(500), `duration` INTEGER COMMENT 'Duration in minutes (for videos)', `status` ENUM('draft', 'published', 'archived') DEFAULT 'draft', `targetAudience` ENUM('members', 'secretary', 'agent', 'agents', 'both') NOT NULL DEFAULT 'members', `views` INTEGER DEFAULT 0, `createdBy` INTEGER NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`createdBy`) REFERENCES `Users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `ChatMessages` (`id` INTEGER auto_increment , `groupId` INTEGER, `senderId` INTEGER NOT NULL, `receiverId` INTEGER, `message` TEXT NOT NULL, `type` ENUM('text', 'file', 'image') DEFAULT 'text', `fileUrl` VARCHAR(500), `isRead` TINYINT(1) DEFAULT false, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`groupId`) REFERENCES `Groups` (`id`) ON DELETE SET NULL ON UPDATE CASCADE, FOREIGN KEY (`senderId`) REFERENCES `Users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`receiverId`) REFERENCES `Users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Notifications` (`id` INTEGER auto_increment , `userId` INTEGER NOT NULL, `type` ENUM('otp', 'registration', 'loan_approval', 'loan_rejection', 'contribution_confirmation', 'fine_issued', 'meeting_reminder', 'announcement', 'vote_created', 'learn_grow_update', 'chat_message', 'general', 'agent_action') NOT NULL, `channel` ENUM('sms', 'email', 'in_app') DEFAULT 'in_app', `title` VARCHAR(255) NOT NULL, `content` TEXT NOT NULL, `recipient` VARCHAR(255) COMMENT 'Phone or email address', `status` ENUM('sent', 'failed', 'pending') DEFAULT 'pending', `read` TINYINT(1) DEFAULT false, `readAt` DATETIME, `error` TEXT, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `Users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Branches` (`id` INTEGER auto_increment , `name` VARCHAR(100) NOT NULL UNIQUE, `code` VARCHAR(20) NOT NULL UNIQUE, `address` TEXT, `district` VARCHAR(100), `sector` VARCHAR(100), `phone` VARCHAR(20), `email` VARCHAR(100), `managerId` INTEGER, `status` ENUM('active', 'inactive') DEFAULT 'active', `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`managerId`) REFERENCES `Users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `MemberApplications` (`id` INTEGER auto_increment , `userId` INTEGER NOT NULL, `groupId` INTEGER NOT NULL, `occupation` VARCHAR(100), `address` TEXT, `reason` TEXT COMMENT 'Why they want to join', `status` ENUM('pending', 'approved', 'rejected') DEFAULT 'pending', `reviewedBy` INTEGER, `reviewDate` DATETIME, `rejectionReason` TEXT, `documents` JSON COMMENT 'Array of document URLs', `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `Users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`groupId`) REFERENCES `Groups` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`reviewedBy`) REFERENCES `Users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `AuditLogs` (`id` INTEGER auto_increment , `userId` INTEGER NOT NULL, `action` VARCHAR(100) NOT NULL, `entityType` VARCHAR(50) COMMENT 'Loan, Contribution, User, etc.', `entityId` INTEGER, `details` JSON, `ipAddress` VARCHAR(50), `userAgent` VARCHAR(255), `createdAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `Users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `SupportTickets` (`id` INTEGER auto_increment , `userId` INTEGER NOT NULL, `subject` VARCHAR(255) NOT NULL, `message` TEXT NOT NULL, `category` ENUM('technical', 'account', 'loan', 'contribution', 'other') DEFAULT 'other', `status` ENUM('open', 'in_progress', 'resolved', 'closed') DEFAULT 'open', `priority` ENUM('low', 'medium', 'high', 'urgent') DEFAULT 'medium', `assignedTo` INTEGER, `resolution` TEXT, `resolvedAt` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `Users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`assignedTo`) REFERENCES `Users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Settings` (`id` INTEGER auto_increment , `key` VARCHAR(100) NOT NULL UNIQUE, `value` TEXT, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `LoanProducts` (`id` INTEGER auto_increment , `name` VARCHAR(100) NOT NULL, `description` TEXT, `interestRate` DECIMAL(5,2) NOT NULL DEFAULT 0, `maxAmount` DECIMAL(15,2) NOT NULL DEFAULT 0, `minAmount` DECIMAL(15,2) NOT NULL DEFAULT 0, `termMonths` INTEGER NOT NULL DEFAULT 0, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `MessageTemplates` (`id` INTEGER auto_increment , `userId` INTEGER NOT NULL COMMENT 'User who created/owns this template', `groupId` INTEGER COMMENT 'Group this template belongs to (for group-specific templates)', `name` VARCHAR(255) NOT NULL COMMENT 'Template name (e.g., \"Contribution Reminder\")', `subject` VARCHAR(255) COMMENT 'Message subject/title', `content` TEXT NOT NULL COMMENT 'Template content with placeholders like [Member Name], [Amount], etc.', `type` ENUM('contribution_reminder', 'loan_payment_reminder', 'fine_notification', 'general_announcement', 'custom') NOT NULL DEFAULT 'custom', `isDefault` TINYINT(1) DEFAULT false COMMENT 'Whether this is a default system template', `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `Users` (`id`), FOREIGN KEY (`groupId`) REFERENCES `Groups` (`id`)) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `ComplianceRules` (`id` INTEGER auto_increment , `groupId` INTEGER NOT NULL, `title` VARCHAR(255) NOT NULL, `description` TEXT NOT NULL, `category` ENUM('Financial', 'Attendance', 'Conduct', 'Procedure', 'General') DEFAULT 'General', `status` ENUM('active', 'inactive', 'archived') DEFAULT 'active', `createdBy` INTEGER NOT NULL, `updatedBy` INTEGER, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`groupId`) REFERENCES `Groups` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`createdBy`) REFERENCES `Users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`updatedBy`) REFERENCES `Users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `ComplianceViolations` (`id` INTEGER auto_increment , `groupId` INTEGER NOT NULL, `ruleId` INTEGER NOT NULL, `memberId` INTEGER NOT NULL, `description` TEXT NOT NULL, `severity` ENUM('low', 'medium', 'high') DEFAULT 'medium', `status` ENUM('pending', 'under-review', 'resolved', 'dismissed') DEFAULT 'pending', `reportedBy` INTEGER NOT NULL, `resolvedBy` INTEGER, `resolutionNotes` TEXT, `reportedDate` DATETIME, `resolvedDate` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`groupId`) REFERENCES `Groups` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`ruleId`) REFERENCES `ComplianceRules` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`memberId`) REFERENCES `Users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`reportedBy`) REFERENCES `Users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`resolvedBy`) REFERENCES `Users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Documents` (`id` INTEGER auto_increment , `groupId` INTEGER NOT NULL, `title` VARCHAR(255) NOT NULL, `description` TEXT, `fileUrl` VARCHAR(500) NOT NULL, `fileName` VARCHAR(255), `fileType` VARCHAR(50), `fileSize` INTEGER, `category` ENUM('contribution', 'loan', 'meeting', 'announcement', 'compliance', 'report', 'other') DEFAULT 'other', `uploadedBy` INTEGER NOT NULL, `uploadedByRole` ENUM('Secretary', 'Cashier', 'Group Admin', 'System Admin') NOT NULL, `referenceType` VARCHAR(50), `referenceId` INTEGER, `status` ENUM('active', 'archived', 'deleted') DEFAULT 'active', `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`groupId`) REFERENCES `Groups` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`uploadedBy`) REFERENCES `Users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `TrainingProgress` (`id` INTEGER auto_increment , `userId` INTEGER NOT NULL, `contentId` INTEGER NOT NULL, `status` ENUM('not_started', 'in_progress', 'completed') NOT NULL DEFAULT 'not_started', `progressPercentage` INTEGER NOT NULL DEFAULT 0 COMMENT 'Progress percentage (0-100)', `timeSpent` INTEGER NOT NULL DEFAULT 0 COMMENT 'Time spent in minutes', `completedAt` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `Users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`contentId`) REFERENCES `LearnGrowContents` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `ScheduledAudits` (`id` INTEGER auto_increment , `groupId` INTEGER NOT NULL, `scheduledBy` INTEGER NOT NULL, `auditType` ENUM('compliance_check', 'financial_audit', 'group_verification', 'investigation') NOT NULL DEFAULT 'compliance_check', `scheduledDate` DATETIME NOT NULL, `status` ENUM('scheduled', 'in_progress', 'completed', 'cancelled') NOT NULL DEFAULT 'scheduled', `description` TEXT, `checklist` JSON COMMENT 'JSON array of checklist items with status', `findings` TEXT, `recommendations` TEXT, `completedAt` DATETIME, `completedBy` INTEGER, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`groupId`) REFERENCES `Groups` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`scheduledBy`) REFERENCES `Users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`completedBy`) REFERENCES `Users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB;

SET FOREIGN_KEY_CHECKS = 1;